# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=1024]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-merge-conflict
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["-S"]
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
    -   id: vulture
        args:
        -   ./
        -   "--exclude"
        -   ".venv/"
        -   "--ignore-names"
        -   "start_call,received_headers"
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: ["--config", "setup.cfg"]
        additional_dependencies: [
            flake8-bandit,
            flake8-bugbear,
            flake8-eradicate,
            flake8-fixme,
            flake8-isort,
            flake8-mutable,
            flake8-quotes,
            flake8-variables-names
        ]
-   repo: https://github.com/PyCQA/pylint
    rev: v2.17.0
    hooks:
    -   id: pylint
        args: ["--rcfile", "setup.cfg"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
    -   id: mypy
